name: CI-CD

on:
  push:
    branches: ["main"]

jobs:
  CI:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3.1.0

      - name: Set up Node.js - Backend
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Instalação de Dependências - Backend
        run: npm install
        working-directory: ./src/Backend

      - name: Instalação de Dependências do Jest - Backend
        run: npm install --save-dev jest
        working-directory: ./src/Backend

      - name: Adicionando Permissões - Backend
        run: chmod -R 777 node_modules
        working-directory: ./src/Backend

      - name: Testes Unitários - Backend
        run: npx jest
        working-directory: ./src/Backend

      - name: Set up Node.js - Frontend
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Instalação de Dependências - Frontend
        run: npm install
        working-directory: ./src/Frontend

      - name: Yarn Install - Frontend
        run: yarn install
        working-directory: ./src/Frontend

      - name: Adicionando Dependência - react-native-vector-icons
        run: yarn add react-native-vector-icons
        working-directory: ./src/Frontend

      - name: Instalação Global - Expo CLI
        run: npm install --global expo-cli
        working-directory: ./src/Frontend

      - name: Adicionando Dependência - expo-font
        run: yarn add expo-font
        working-directory: ./src/Frontend

      - name: Expo Upgrade - Frontend
        run: expo upgrade
        working-directory: ./src/Frontend

      - name: Yarn Global Add - react-native-cli
        run: yarn global add react-native-cli
        working-directory: ./src/Frontend

      - name: Expo Install - expo-font
        run: expo install expo-font
        working-directory: ./src/Frontend

      - name: Adicionando Dependência - react-native-gesture-handler
        run: yarn add react-native-gesture-handler
        working-directory: ./src/Frontend

      - name: Adicionando Dependência de Desenvolvimento - react-test-renderer
        run: yarn add --dev react-test-renderer
        working-directory: ./src/Frontend

      - name: Adicionando Dependência de Desenvolvimento - Jest
        run: yarn add --dev jest
        working-directory: ./src/Frontend

      - name: Adicionando Dependência de Desenvolvimento - @testing-library/react-native
        run: yarn add --dev @testing-library/react-native
        working-directory: ./src/Frontend

      - name: Testes - Frontend
        run: yarn test
        working-directory: ./src/Frontend

  CD:
    runs-on: ubuntu-latest
    needs: [CI]
    steps:
      - uses: actions/checkout@v3.1.0

      - name: Set up Node.js - Backend
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Instalação de Dependências - Backend
        run: npm install
        working-directory: ./src/Backend

      - name: Instalação de Dependências do Jest - Backend
        run: npm install --save-dev jest
        working-directory: ./src/Backend

      - name: Adicionando Permissões - Backend
        run: chmod -R 777 node_modules
        working-directory: ./src/Backend

      - name: Testes Unitários - Backend
        run: npx jest
        working-directory: ./src/Backend

      - name: Set up Node.js - Frontend
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Instalação de Dependências - Frontend
        run: npm install --force
        working-directory: ./src/Frontend

      - name: Yarn Install - Frontend
        run: yarn install
        working-directory: ./src/Frontend

      - name: Adicionando Dependência - react-native-vector-icons
        run: yarn add react-native-vector-icons
        working-directory: ./src/Frontend

      - name: Instalação Global - Expo CLI
        run: npm install --global expo-cli
        working-directory: ./src/Frontend

      - name: Adicionando Dependência - expo-font
        run: yarn add expo-font
        working-directory: ./src/Frontend

      - name: Expo Upgrade - Frontend
        run: expo upgrade
        working-directory: ./src/Frontend

      - name: Yarn Global Add - react-native-cli
        run: yarn global add react-native-cli
        working-directory: ./src/Frontend
        
      - name: Expo Install - expo-font
        run: expo install expo-font
        working-directory: ./src/Frontend

      - name: Adicionando Dependência - react-native-gesture-handler
        run: yarn add react-native-gesture-handler
        working-directory: ./src/Frontend

      - name: Adicionando Dependência de Desenvolvimento - react-test-renderer
        run: yarn add --dev react-test-renderer
        working-directory: ./src/Frontend

      - name: Adicionando Dependência de Desenvolvimento - Jest
        run: yarn add --dev jest
        working-directory: ./src/Frontend

      - name: Adicionando Dependência de Desenvolvimento - @testing-library/react-native
        run: yarn add --dev @testing-library/react-native
        working-directory: ./src/Frontend

      - name: Testes - Frontend
        run: yarn test
        working-directory: ./src/Frontend
